name: Build and Publish Docker Image
on:
  push:
    branches:
      - main # Déclenche le workflow sur les push vers la branche main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest # Utilise la dernière version d'Ubuntu pour exécuter les jobs
    
    steps:
      - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code
        uses: actions/checkout@v4.1.2
        
      - uses: hadolint/hadolint-action@v3.1.0 # Utilise Hadolint pour lint le Dockerfile et assure que les meilleures pratiques sont suivies
        with:
          dockerfile: Dockerfile
        continue-on-error: true
        
      #TP3

      - name: 'Login via Azure CLI'
        uses: Azure/login@v2.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push image to ACR
        uses: Azure/docker-login@v1.0.1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.MY_EFREI_IDENT }}:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.MY_EFREI_IDENT }}:${{ github.sha }}

      - name: Tag and push image to Docker Hub
        run: |
          docker tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.MY_EFREI_IDENT }}:${{ github.sha }} lisax105/efrei-devops-tp3:${{ github.sha }}
          docker lisax105/efrei-devops-tp3:${{ github.sha }}
         
      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: devops-${{ secrets.MY_EFREI_IDENT }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.MY_EFREI_IDENT }}:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: ${{ secrets.MY_EFREI_IDENT }}
          location: 'france central'
          ports: 80
          environment-variables: API_KEY=${{ secrets.API_KEY }}
            
      - run: echo " This job's status is ${{ job.status }}."
