name: Build and Publish Docker
on:
  push:
    branches:
      - main 
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: lisax105/efrei-devops-tp2:latest
          
      - run: echo " This job's status is ${{ job.status }}."
